### ISSUE TITLE
BlockSniper 4.0.0 release TODO

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/BlockSniper#120]
#### Description
A number of bugs need to be fixed and features need to be added before BlockSniper 4.0.0 is released. The below list will display bugs found that need to be fixed and their status.

**Bugs**
- [x] Using /undo on trees does not remove the entire tree as expected.
- [x] Hollow spheres, ellipsoids and cylinders do not function properly.
- [x] Async reverts should not start async tasks.

**Features**
- [x] Add a ReplaceTarget brush that replaces all blocks of the type of the block looked at.
