### ISSUE TITLE
TODO List: Version 1.4.0

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/BlockSniper#51]
**TODO List for BlockSniper version 1.4.0**

**Cloning Changes**
- [x] Rewrite of cloning system.
- [x] Add schematic clone type saving.
- [x] Add schematic paste type.
- [x] Add a way to use any shape for a clone type.

**Code Improvements**
- [x] Better usage of OOP, especially with cloning.
- [x] Less duplicated code.
- [x] Strict types.

**Configuration**
- [x] Add an option to copy air blocks as well.

**Undo/Redo Changes**
- [x] Add Undo-ing of Redo.
- [x] Add undo/redo file history, for easier checking if a modification has been started with tick spread brush.

**Command Improvements**
- [x] Add Vanilla MCPE command syntax.
- [x] Add available parameters for commands. (/brush --> Size, Type, Shape, etc...)
- [x] Optimize command overloads code as much as possible.

**Tick Spread modifications** 
- [x] Add tick spread out brushing. 
- [x] Add tick spread out undo/redo. 
- [ ] ~~Add tick spread out pasting.~~
- [ ] ~~Add tick spread out cloning.~~

**Bug Fixes**
- [x] Fix Schematic saving not working.
- [x] Fix Redo not working.
- [x] Fix tick spread out undo/redo not working correctly. 
- [x] Include libschematic as a virion

**Comment by TheDiamondYT1** [comment]
Since its in the same organization, add support for creating faction plots with this plugin?

**Comment by Sandertv** [comment]
Interesting idea? How did you envision that though?

**Comment by TheDiamondYT1** [comment]
Almost done with this list?

**Comment by TheDiamondYT1** [comment]
Now we need to submit libschematic as a virion and we can include that instead of the submodule

**Comment by Sandertv** [comment]
Sorta yeah. I'm not sure if I should look into integration with libgeom with this release already or next release though...

**Comment by TheDiamondYT1** [comment]
@SOF3 How would we submit a virion to Poggit?

**Comment by Sandertv** [comment]
Alright guess I'll be closing this.
