### ISSUE TITLE
TODO List: 1.5.0/2.0.0

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/BlockSniper#60]
**TODO List for BlockSniper 1.5.0/2.0.0:**
The Asynchronous update.

This update will overwrite the 1.4.0 update of BlockSniper, as not enough use could be found in that version, and new features in 1.5.0/2.0.0 obsolete the features in 1.4.0.

**Custom UI**
- [x] #64 

**Asynchronous**
- [x] Implement a (not so) basic asynchronous system with the types and shapes
- [x] Implement asynchronous brushing.
- [x] Implement asynchronous undo/redo.
- [x] Implement asynchronous pasting. (Especially schematics)

**API**
- [x] Properly move every function to the classes that should have them, not **could** have them.
- [x] Implement an easy to use API function for asynchronous modifications.

**Translations**
- [x] Add a completely new translation system that auto completes.
- [x] Remove old translations. ( :( )
- [x] Add new translations.

**Bug Fixes**
- [ ] Fix any bug that can be found. Get everything stable once again.

**Comment by SOF3** [comment]
Wanna use this? https://gist.github.com/SOF3/3ed74c40f453fe08dadf5978a7cbdd88

**Comment by Sandertv** [comment]
I am actually interested in making such a world edit plugin, but BlockSniper isn't really the kind of world editing plugin that all those ideas should be included in. Some of them are definitely a good idea though.

**Comment by TheDiamondYT1** [comment]
Should i cleanup and merge the 1.4 branch then or is that a terrible dumb idea that will cause the moon to explode?

**Comment by Sandertv** [comment]
The code might turn nuclear and explode when you try to enable it but I guess you could. 😄

**Comment by Sandertv** [comment]
Nah just kidding go ahead.

**Comment by Sandertv** [comment]
Gg I've done it again. I've messed up everything and merged the Threaded-Editing in the 1.4.0 branch. #gitgud. Rip the plans.

**Comment by Sandertv** [comment]
Added new translation system to the list. It'll be auto completable by IDEs, and use auto generated constants.

**Comment by Sandertv** [comment]
Due to the many (backwards) incompatible changes and huge updates/new features this update, the version will likely be bumped to 2.0.0 instead of 1.5.0.

**Comment by zurkhan** [comment]
Server thread/CRITICAL ErrorException: "Undefined index: Configuration-Version" (EXCEPTION) in "BlockSniper.phar/src/BlockHorizons/BlockSniper/data/ConfigData" at line 65 is the bug for your plugin please make a working blocksniper id even donate money for one

**Comment by Sandertv** [comment]
Just delete your settings.yml and it's fixed.

**Comment by zurkhan** [comment]
Where would that be located?
